
services:
  backend:
    image: jagwar7/flash-auth-app:latest
    container_name: express-backend
    restart: always
    ports:
      - "5000:${PORT:-5900}"
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/firebase_config.json
    volumes:
      - /home/ubuntu/firebase-auth.json:/app/config/firebase_config.json
    depends_on:
      redis:
        condition: service_healthy # WAIT UNTIL REDIS STARTS 
    networks:
      - app-network



  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 256M #MEMEROY ALLOCATED FOR REDIS CACHING

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  
    networks:
      - app-network
    

volumes:
  redis_data:
  
networks:
  app-network:
    driver: bridge
